---
title: "R Notebook"
output: html_notebook
---


```{r}
library(mapproj)
library(tidyverse)
library(ggthemes)
library(forcats)
library(lubridate)
```

```{r}
filename <- './boston_crime/data/crime.csv'
incident_data <- read_csv(filename)
```

```{r}
incident_data <- incident_data %>% rename(lng = Long, lat = Lat)
```


```{r}
offense_group <- incident_data %>% group_by(OFFENSE_CODE_GROUP)  %>% summarise(count = n()) %>% arrange(-count)
write_csv(offense_group, './boston_crime/data/offense_group.csv')
```

```{r}
incident_data %>% filter(OFFENSE_CODE_GROUP == 'Drug Violation') %>%
  ggplot(aes(x = as.factor(YEAR))) +
  geom_bar(stat = 'count') 
```


```{r}
incident_data <- incident_data %>% mutate(date = ymd_hms(OCCURRED_ON_DATE), hour = hour(date))
```

```{r}
incident_data %>% mutate(month = month(date, abbr = TRUE, label = TRUE)) %>%  
  group_by(month) %>% summarise(count = n()) %>%
  ggplot(aes(x = month, y = count, group = 1)) + 
  geom_line()
```

```{r}
incident_data %>% #group_by(hour) %>% summarise(count = n()) %>%
  ggplot(aes(x = hour)) +
  geom_bar()

```

```{r}
byHour <- incident_data %>% group_by(OFFENSE_CODE_GROUP) %>% mutate(group_total = n()) %>% 
  group_by(OFFENSE_CODE_GROUP, hour) %>% summarise(count = n(), per = count / group_total[1])
```

```{r}
byGroup <- incident_data %>% group_by(OFFENSE_CODE_GROUP) %>% summarise(count = n()) %>% arrange(-count)
topGroups <- byGroup %>% head(n = 20)
```


```{r}
byHour %>% filter(OFFENSE_CODE_GROUP %in% topGroups$OFFENSE_CODE_GROUP) %>%
  ggplot(aes(x = hour, y = per)) + 
  geom_bar(stat = "identity") + 
  facet_wrap(~ OFFENSE_CODE_GROUP)
```

```{r}
topGroups %>% 
      ggplot(aes(x = fct_rev(fct_inorder(OFFENSE_CODE_GROUP)), y = count)) +
      coord_flip() + 
      geom_bar(stat = "identity") +
      theme_bw() +
      labs(title = "Top Groups by Total Count")
```

```{r, fig.width=4}
incident_data %>% filter(lng < -60) %>% filter(OFFENSE_CODE_GROUP %in% topGroups$OFFENSE_CODE_GROUP) %>%
  ggplot(aes(x = lng, y = lat)) +
  geom_point(size = 0.4, alpha = 1 / 100) + 
  facet_wrap(~ OFFENSE_CODE_GROUP) +
  theme_map() + 
  coord_quickmap() +
  #coord_map("mercator") +
  labs(title = "")
```



```{r, message=FALSE, warning=FALSE, include=FALSE}

theme_map <- function(base_size=9, base_family="") {
    require(grid)
    theme_bw(base_size=base_size, base_family=base_family) %+replace%
    theme(axis.line=element_blank(),
          axis.text=element_blank(),
          axis.ticks=element_blank(),
          axis.title=element_blank(),
          panel.background=element_blank(),
          panel.border=element_blank(),
          panel.grid=element_blank(),
          panel.margin=unit(0, "lines"),
          plot.background=element_blank(),
          legend.justification = c(0,0), 
          legend.position = c(0,0)
          )
}


```